# Generated by Django 2.2.13 on 2020-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
